from Workpackage import Workpackage
from Project import project

myInput = input("Dein Projekt?")
myP = project(myInput)
print(Workpackage.sum_duration)
print(Workpackage.cnt_ws)
myworkpackage = Workpackage("WBS 1.0")
myworkpackage.SetDuration(8)
myworkpackage.SetStatus("In Progress")
myworkpackage.PrintAll()
myP.AddWbs(myworkpackage)
d = myworkpackage.GetDuration()
print(f"Ich brauche noch {d} Stunden")
print(f"Mein Status ist {myworkpackage.GetStatus()}")
print(f"Ich bin {myworkpackage.GetName()}")
print(Workpackage.sum_duration)
print(Workpackage.cnt_ws)
mywb2 = Workpackage("WBS 2.0")
mywb2.SetDuration(4)
mywb2.SetStatus("In Progress")
mywb2.PrintAll()
myP.AddWbs(mywb2)
for i in Workpackage.all_wbs:
    i.PrintAll()
print(Workpackage.sum_duration)
print(Workpackage.cnt_ws)
print(f"Mein Projekt {myP.GetName()} braucht {myP.GetDuration()} Stunden")
print(f"Und hat {myP.GetWbsCnt()} Workpackages")
myP.PrintAll()